datana:
  jms:
    brokerUrl: tcp://172.29.40.42:61616
camel:
  springboot:
    main-run-controller: true
    jmx-enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'

debug: true
logging:
  level:
    org:
      hibernate:
        engine:
          transaction: DEBUG
        SQL: DEBUG
      springframework: DEBUG
    ru:
      sbrf:
        ais:
          microservices:
            safe: DEBUG
    sql: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'

#camel:
#  component:
#    activemq:
#      brokerURL: tcp://172.29.40.42:61616
#      auto-startup: true
#  springboot:
#    main-run-controller: true
#

